### PR TITLE
issue319: Update the npm packages of BasicServices and ApplicationPattern to 2.0.2-alpha.2

### PR DESCRIPTION
**Pull request by sunil-kumar-meena**
Fixes https://github.com/openBackhaul/ExecutionAndTraceLog/issues/319

Reviewer @PrathibaJee

### CODE REVIEW

**Review by PrathibaJee — CHANGES_REQUESTED** [review]
Please check whether package-lock.json shall also be included.

**Comment by sunil-kumar-meena** [comment]
> Please check whether package-lock.json shall also be included.

done

**Review by PrathibaJee — CHANGES_REQUESTED** [review]
Could you please check whether package-lock.json consists of the following, 
    "onf-core-model-ap": "2.0.2-alpha.2",
    "onf-core-model-ap-bs": "2.0.2-alpha.2"
 I could not able to see that change in the difference.

**Comment by sunil-kumar-meena** [comment]
> Could you please check whether package-lock.json consists of the following,
> "onf-core-model-ap": "2.0.2-alpha.2",
> "onf-core-model-ap-bs": "2.0.2-alpha.2"
> I could not able to see that change in the difference.

Please check now

**Review by IswaryaaS — APPROVED** [review]

**Pull request closed without merging**
